### ISSUE TITLE
problems with running

### ISSUE THREAD

**Issue by iiilia** [antter7/task_for_hiring#1]
Добрый день! при запуске обнаружил несколько проблем

1) не работает сборка контейнера (в `requirements.txt` зря прописан модуль `re`, так как он встроенный в питон)
2) контейнер не запускается (с помощью команды `docker run -it -v ~/main/task-for-hiring-data:/task-for-hiring-data task_for_hiring python lib/run.py`, которая прописана ридми) - файл `run.py` находится по другому пути
3) не импортится модуль `pymorphy2`, так как он не установлен

когда удастся исправить эти проблемы, можете заменшить меня в этом ишью?)

**Comment by antter7** [comment]
кажется готово
